# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3'

services:
  # mariadb:
  #   image: mariadb:10.6
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - db-data:/var/lib/mysql
    
    
  php:
    build:
     dockerfile: Docker/php/Dockerfile
    volumes:
      # - ./Docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./:/app
    working_dir: /app
    
    # depends_on:
    #   - mariadb
    
  nginx:
    build: 
      dockerfile: Docker/nginx/Dockerfile
    volumes:
      # - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
      
    depends_on:
      - php
    ports:
      - 8003:8003
      


  # node:
  #   image: docker.io/node
  #   volumes:
  #     - './:/app'
  #   working_dir: /app
  #   command: bash -c "npm install && npm run watch" # install and run watch for npm (if it work)

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8888:80
  #   environment:
  #     - PMA_ARBITRARY=1

# volumes:
#   db-data:
